FROM node:21

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

RUN npx prisma generate

ENV NODE_ENV production
RUN npx next telemetry disable
RUN npx prisma db seed
RUN npm run build

EXPOSE 3000
ENV PORT 3000
ENV HOSTNAME 0.0.0.0

CMD ["npm","run","start"]